_target_: src.logger.WandBWriter
project_name: "soundstream"
entity: null
run_name: "librispeech-train"
mode: "online"
loss_names: ["gen_loss", "discr_loss", "gen_adv_loss", "feat_loss", "commit_loss", "rec_loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
